PREFIX fg:     <{{FG_BASE_URI}}>
PREFIX fgdata: <{{FGDATA_BASE_URI}}>
PREFIX foaf:   <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bibo:   <http://purl.org/ontology/bibo/>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?title ?doi ?date ?journal
       (GROUP_CONCAT(DISTINCT ?source; separator=", ") AS ?sources)
       ?status
WHERE {
    ?assertion a fg:PublicationAssertion ;
               fg:faculty ?faculty ;
               fg:work ?work ;
               fg:status ?statusNode ;
               fg:source ?sourceNode .

    ?faculty foaf:name ?name .
    ?work dcterms:title ?title .

    ?statusNode rdfs:label ?status .
    ?sourceNode rdfs:label ?source .

    OPTIONAL { ?work bibo:doi ?doi }
    OPTIONAL { ?work dcterms:date ?date }
    OPTIONAL { ?work fg:journal ?journal }

    FILTER (?statusNode != fg:rejected)
}
GROUP BY ?name ?title ?doi ?date ?journal ?status
ORDER BY ?name DESC(?date)
