#!/usr/bin/env bash

# Stage generated RDF for a QLever index build.
#
# QLever ingests at index build time rather than over HTTP, so this script does
# not "load" anything by itself: it copies the RDF into QLever's data directory
# and prints the index/start commands to run there. That is the whole workflow --
# there is no upload endpoint to POST to.
#
# There is also no graph URI to configure, unlike the Fuseki loader: QLever
# indexes into the default graph, which is exactly where the queries in queries/
# read from, since none of them carries a GRAPH clause.
#
# Usage: ./scripts/load_graph_qlever.sh [qlever_endpoint]
# Example: ./scripts/load_graph_qlever.sh http://localhost:7001

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RDF_DIR="${PROJECT_ROOT}/data/output/rdf"
COMBINED_FILE="${RDF_DIR}/faculty-all.ttl"

DEFAULT_QLEVER_ENDPOINT="http://localhost:7001"
DEFAULT_DATA_DIR="${PROJECT_ROOT}/qlever-data"

print_usage() {
    echo "Usage: $0 [qlever_endpoint]"
    echo ""
    echo "Stage faculty RDF for a QLever index build."
    echo ""
    echo "Arguments:"
    echo "  qlever_endpoint   QLever SPARQL endpoint, used only to verify an"
    echo "                    already-running server (default: ${DEFAULT_QLEVER_ENDPOINT})"
    echo ""
    echo "Environment:"
    echo "  QLEVER_DATA_DIR   Where to stage the RDF and build the index"
    echo "                    (default: ${DEFAULT_DATA_DIR})"
    echo ""
    echo "Prerequisites:"
    echo "  - Combined RDF file generated by: uv run python3 main.py"
    echo "  - qlever CLI, or Docker -- see docs/qlever-setup.md"
}

# A help flag occupies $1, so defaults must be in place before the usage text.
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    print_usage
    exit 0
fi

QLEVER_ENDPOINT="${1:-${DEFAULT_QLEVER_ENDPOINT}}"
QLEVER_DATA_DIR="${QLEVER_DATA_DIR:-${DEFAULT_DATA_DIR}}"

if [[ ! -f "${COMBINED_FILE}" ]]; then
    echo "ERROR: Combined RDF file not found: ${COMBINED_FILE}" >&2
    echo "Run 'uv run python3 main.py' first to generate RDF output." >&2
    exit 1
fi

LINE_COUNT=$(wc -l < "${COMBINED_FILE}")
echo "Staging ${COMBINED_FILE} (${LINE_COUNT} lines) for QLever"

mkdir -p "${QLEVER_DATA_DIR}"
cp "${COMBINED_FILE}" "${QLEVER_DATA_DIR}/faculty-all.ttl"
echo "RDF copied to ${QLEVER_DATA_DIR}/faculty-all.ttl"
echo ""

# Print the index/start steps for whichever toolchain is actually installed.
print_next_steps() {
    if command -v qlever &> /dev/null; then
        echo "Next steps (qlever CLI found):"
        echo "  cd ${QLEVER_DATA_DIR}"
        echo "  qlever stop     # no-op if nothing is running"
        echo "  qlever index    # rebuild the index with the new data"
        echo "  qlever start"
        return 0
    fi

    echo "No qlever CLI on PATH. Either install it (pip install qlever) or use"
    echo "Docker directly:"
    echo "  cd ${QLEVER_DATA_DIR}"
    echo "  docker run --rm -v \"\$(pwd):/data\" -w /data adfreiburg/qlever \\"
    echo "      IndexBuilderMain -f faculty-all.ttl -i faculty \\"
    echo "      -s '{\"ascii-prefixes-only\": false}'"
    echo "  docker run -d --name qlever-faculty -p 7001:7001 \\"
    echo "      -v \"\$(pwd):/data\" -w /data adfreiburg/qlever \\"
    echo "      ServerMain -i faculty -p 7001"
    echo ""
    echo "See docs/qlever-setup.md for the full workflow."
}

print_next_steps

# Re-indexing replaces the served data, so a count from the *running* server
# still reflects the previous index. Report it as the "before" number rather
# than as confirmation that this staging worked.
echo ""
if curl --silent --fail --output /dev/null --max-time 5 "${QLEVER_ENDPOINT}" 2>/dev/null; then
    COUNT_RESPONSE=$(curl --silent --max-time 10 \
        --header "Accept: application/sparql-results+json" \
        --data-urlencode "query=SELECT (COUNT(*) AS ?count) WHERE { ?s ?p ?o }" \
        "${QLEVER_ENDPOINT}" 2>/dev/null) || COUNT_RESPONSE=""

    TRIPLE_COUNT=$(echo "${COUNT_RESPONSE}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(data['results']['bindings'][0]['count']['value'])
" 2>/dev/null) || TRIPLE_COUNT="unknown"

    echo "Server at ${QLEVER_ENDPOINT} currently serves ${TRIPLE_COUNT} triples"
    echo "(the previous index -- re-index and restart to serve what was just staged)."
else
    echo "No server responding at ${QLEVER_ENDPOINT}. Build the index and start one."
fi
