#!/usr/bin/env bash

# Load generated RDF Turtle files into an Apache Jena Fuseki instance.
# Uses Fuseki's Graph Store Protocol (HTTP POST) endpoint.
#
# The target named graph is derived from FG_BASE_URI, the same setting the
# pipeline generates IRIs under, so the two cannot drift apart.
#
# Usage: ./scripts/load_graph_fuseki.sh [fuseki_url] [dataset_name]
# Example: ./scripts/load_graph_fuseki.sh http://localhost:3030 faculty

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RDF_DIR="${PROJECT_ROOT}/data/output/rdf"
COMBINED_FILE="${RDF_DIR}/faculty-all.ttl"
DEFAULT_FUSEKI_URL="http://localhost:3030"
DEFAULT_DATASET="faculty"

# Must match DEFAULT_BASE_URI in src/config.py.
DEFAULT_BASE_URI="http://example.org/faculty-graph/"
EXIT_CONFIG_ERROR=2

# Read one KEY=value assignment from .env. The file is parsed, never sourced:
# it is configuration, and sourcing it would execute whatever it contains.
#
# Returns non-zero when the key is absent, so that a key present but empty
# stays distinguishable from a key that was never set -- an empty value is a
# mistake worth reporting, not a reason to fall back to a default.
read_env_file_value() {
    local key="$1"
    local env_file="${PROJECT_ROOT}/.env"

    if [[ ! -f "${env_file}" ]]; then
        return 1
    fi

    local line
    line="$(grep -E "^[[:space:]]*${key}[[:space:]]*=" "${env_file}" | tail -1)" || true
    if [[ -z "${line}" ]]; then
        return 1
    fi

    # Strip the key, surrounding whitespace, and optional quotes -- .env files
    # are written both quoted and bare.
    local value="${line#*=}"
    value="$(printf '%s' "${value}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    value="$(printf '%s' "${value}" | sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'$/\1/")"
    printf '%s' "${value}"
}

# Reject a base IRI that would produce an unusable graph name.
# Mirrors the validation in src/config.py base_uri().
validate_base_uri() {
    local value="$1"

    if [[ "${value}" != http://* && "${value}" != https://* ]]; then
        echo "ERROR: FG_BASE_URI must start with http:// or https:// (got '${value}')" >&2
        return 1
    fi

    if [[ "${value}" != */ ]]; then
        echo "ERROR: FG_BASE_URI must end with '/' (got '${value}')" >&2
        return 1
    fi

    # The graph name is interpolated into a query string, so a value containing
    # a separator would silently truncate the upload URL.
    if [[ "${value}" =~ [[:space:]\&\?\#] ]]; then
        echo "ERROR: FG_BASE_URI must not contain whitespace, '&', '?', or '#' (got '${value}')" >&2
        return 1
    fi

    return 0
}

# Decide which named graph to load into.
# Precedence: explicit GRAPH_URI, then FG_BASE_URI from the shell, then
# FG_BASE_URI from .env, then the default -- the same order the pipeline uses,
# so an exported override applies to both without editing a file.
resolve_graph_uri() {
    if [[ -n "${GRAPH_URI+set}" ]]; then
        if [[ -z "${GRAPH_URI}" ]]; then
            echo "ERROR: GRAPH_URI is set but empty. Unset it to derive the graph" >&2
            echo "       name from FG_BASE_URI, or give it a graph IRI." >&2
            return 1
        fi
        printf '%s' "${GRAPH_URI}"
        return 0
    fi

    # An empty FG_BASE_URI is rejected rather than defaulted, matching
    # src/config.py: the pipeline that wrote the data would have failed on it,
    # so the loader must not quietly pick a different namespace.
    local base_uri
    if [[ -n "${FG_BASE_URI+set}" ]]; then
        base_uri="${FG_BASE_URI}"
    elif ! base_uri="$(read_env_file_value "FG_BASE_URI")"; then
        base_uri="${DEFAULT_BASE_URI}"
    fi

    if ! validate_base_uri "${base_uri}"; then
        return 1
    fi

    printf '%s' "${base_uri}data"
}

print_usage() {
    echo "Usage: $0 [fuseki_url] [dataset_name]"
    echo ""
    echo "Load faculty RDF data into Apache Jena Fuseki."
    echo ""
    echo "Arguments:"
    echo "  fuseki_url     Fuseki server URL (default: http://localhost:3030)"
    echo "  dataset_name   Target dataset name (default: faculty)"
    echo ""
    echo "Environment:"
    echo "  FG_BASE_URI    Namespace the RDF was generated under. The named graph"
    echo "                 is this plus 'data'. Read from the shell, else from"
    echo "                 .env, else '${DEFAULT_BASE_URI}'."
    echo "  GRAPH_URI      Load into this named graph instead, ignoring FG_BASE_URI."
    echo ""
    echo "Prerequisites:"
    echo "  - Fuseki running at the specified URL"
    echo "  - Dataset '${DATASET}' already created in Fuseki"
    echo "  - Combined RDF file generated by: uv run python3 main.py"
    echo ""
    echo "To create the dataset in Fuseki:"
    echo "  curl -X POST ${FUSEKI_URL}/\$/datasets -d 'dbName=${DATASET}&dbType=tdb2'"
}

# A help flag occupies $1, so the defaults must be in place before the usage
# text is printed -- otherwise it advertises "--help" as the Fuseki URL.
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    FUSEKI_URL="${DEFAULT_FUSEKI_URL}"
    DATASET="${DEFAULT_DATASET}"
    print_usage
    exit 0
fi

FUSEKI_URL="${1:-${DEFAULT_FUSEKI_URL}}"
DATASET="${2:-${DEFAULT_DATASET}}"

if [[ ! -f "${COMBINED_FILE}" ]]; then
    echo "ERROR: Combined RDF file not found: ${COMBINED_FILE}" >&2
    echo "Run 'uv run python3 main.py' first to generate RDF output." >&2
    exit 1
fi

if ! GRAPH_URI="$(resolve_graph_uri)"; then
    exit "${EXIT_CONFIG_ERROR}"
fi

UPLOAD_URL="${FUSEKI_URL}/${DATASET}/data?graph=${GRAPH_URI}"
LINE_COUNT=$(wc -l < "${COMBINED_FILE}")
echo "Loading ${COMBINED_FILE} (${LINE_COUNT} lines)"
echo "Target: ${UPLOAD_URL}"

# Check Fuseki is reachable
if ! curl --silent --fail --output /dev/null "${FUSEKI_URL}/\$/ping" 2>/dev/null; then
    if ! curl --silent --fail --output /dev/null "${FUSEKI_URL}/\$/server" 2>/dev/null; then
        echo "ERROR: Fuseki not reachable at ${FUSEKI_URL}" >&2
        echo "Start Fuseki first, then retry." >&2
        exit 1
    fi
fi

echo "Fuseki reachable. Uploading..."

# Upload using Graph Store Protocol (PUT replaces, POST appends)
# Using PUT to replace the faculty graph on each harvest run
RESPONSE=$(curl --silent --write-out "\n%{http_code}" \
    --request PUT \
    --header "Content-Type: text/turtle" \
    --data-binary "@${COMBINED_FILE}" \
    "${UPLOAD_URL}")

HTTP_CODE=$(echo "${RESPONSE}" | tail -1)
BODY=$(echo "${RESPONSE}" | head -n -1)

if [[ "${HTTP_CODE}" == "200" || "${HTTP_CODE}" == "201" || "${HTTP_CODE}" == "204" ]]; then
    echo "Upload successful (HTTP ${HTTP_CODE})"
else
    echo "ERROR: Upload failed (HTTP ${HTTP_CODE})" >&2
    echo "${BODY}" >&2
    echo ""
    echo "Common fixes:"
    echo "  - Create dataset first:"
    echo "    curl -X POST ${FUSEKI_URL}/\$/datasets -d 'dbName=${DATASET}&dbType=tdb2'"
    echo "  - Check Fuseki logs for details"
    exit 1
fi

# Run a SPARQL query against the dataset and echo the single count it returns.
run_count_query() {
    local query="$1"
    local response

    response=$(curl --silent \
        --header "Accept: application/sparql-results+json" \
        --data-urlencode "query=${query}" \
        "${FUSEKI_URL}/${DATASET}/sparql")

    echo "${response}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(data['results']['bindings'][0]['count']['value'])
" 2>/dev/null || echo "unknown"
}

# Verify by running a count query
echo ""
echo "Verifying load..."
COUNT_QUERY="SELECT (COUNT(*) AS ?count) WHERE { GRAPH <${GRAPH_URI}> { ?s ?p ?o } }"
TRIPLE_COUNT="$(run_count_query "${COUNT_QUERY}")"

echo "Loaded ${TRIPLE_COUNT} triples into graph <${GRAPH_URI}>"

# The shipped queries in queries/ carry no GRAPH clause, so they read the
# default graph. On a stock TDB2 dataset that is empty even after a successful
# named-graph load, and every query returns zero rows with no error to explain
# why. Say so here rather than letting it look like a harvest problem.
DEFAULT_GRAPH_COUNT="$(run_count_query "SELECT (COUNT(*) AS ?count) WHERE { ?s ?p ?o }")"
if [[ "${DEFAULT_GRAPH_COUNT}" == "0" ]]; then
    echo ""
    echo "NOTE: the default graph is empty, and the queries in queries/ do not"
    echo "      use a GRAPH clause, so they will return no rows as loaded."
    echo "      Either enable a union default graph on the dataset:"
    echo "        tdb2:unionDefaultGraph true ;"
    echo "      or query the named graph explicitly:"
    echo "        GRAPH <${GRAPH_URI}> { ... }"
fi

echo ""
echo "Query endpoint: ${FUSEKI_URL}/${DATASET}/sparql"
echo "Web UI: ${FUSEKI_URL}/#/dataset/${DATASET}/query"
