#!/usr/bin/env bash

# Load generated RDF Turtle files into an Apache Jena Fuseki instance.
# Uses Fuseki's Graph Store Protocol (HTTP POST) endpoint.
#
# Usage: ./scripts/load_graph_fuseki.sh [fuseki_url] [dataset_name]
# Example: ./scripts/load_graph_fuseki.sh http://localhost:3030 faculty

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RDF_DIR="${PROJECT_ROOT}/data/output/rdf"
COMBINED_FILE="${RDF_DIR}/faculty-all.ttl"
FUSEKI_URL="${1:-http://localhost:3030}"
DATASET="${2:-faculty}"
GRAPH_URI="http://example.org/faculty-graph/data"

print_usage() {
    echo "Usage: $0 [fuseki_url] [dataset_name]"
    echo ""
    echo "Load faculty RDF data into Apache Jena Fuseki."
    echo ""
    echo "Arguments:"
    echo "  fuseki_url     Fuseki server URL (default: http://localhost:3030)"
    echo "  dataset_name   Target dataset name (default: faculty)"
    echo ""
    echo "Prerequisites:"
    echo "  - Fuseki running at the specified URL"
    echo "  - Dataset '${DATASET}' already created in Fuseki"
    echo "  - Combined RDF file generated by: python3 main.py"
    echo ""
    echo "To create the dataset in Fuseki:"
    echo "  curl -X POST ${FUSEKI_URL}/\$/datasets -d 'dbName=${DATASET}&dbType=tdb2'"
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    print_usage
    exit 0
fi

if [[ ! -f "${COMBINED_FILE}" ]]; then
    echo "ERROR: Combined RDF file not found: ${COMBINED_FILE}" >&2
    echo "Run 'python3 main.py' first to generate RDF output." >&2
    exit 1
fi

UPLOAD_URL="${FUSEKI_URL}/${DATASET}/data?graph=${GRAPH_URI}"
LINE_COUNT=$(wc -l < "${COMBINED_FILE}")
echo "Loading ${COMBINED_FILE} (${LINE_COUNT} lines)"
echo "Target: ${UPLOAD_URL}"

# Check Fuseki is reachable
if ! curl --silent --fail --output /dev/null "${FUSEKI_URL}/\$/ping" 2>/dev/null; then
    if ! curl --silent --fail --output /dev/null "${FUSEKI_URL}/\$/server" 2>/dev/null; then
        echo "ERROR: Fuseki not reachable at ${FUSEKI_URL}" >&2
        echo "Start Fuseki first, then retry." >&2
        exit 1
    fi
fi

echo "Fuseki reachable. Uploading..."

# Upload using Graph Store Protocol (PUT replaces, POST appends)
# Using PUT to replace the faculty graph on each harvest run
RESPONSE=$(curl --silent --write-out "\n%{http_code}" \
    --request PUT \
    --header "Content-Type: text/turtle" \
    --data-binary "@${COMBINED_FILE}" \
    "${UPLOAD_URL}")

HTTP_CODE=$(echo "${RESPONSE}" | tail -1)
BODY=$(echo "${RESPONSE}" | head -n -1)

if [[ "${HTTP_CODE}" == "200" || "${HTTP_CODE}" == "201" || "${HTTP_CODE}" == "204" ]]; then
    echo "Upload successful (HTTP ${HTTP_CODE})"
else
    echo "ERROR: Upload failed (HTTP ${HTTP_CODE})" >&2
    echo "${BODY}" >&2
    echo ""
    echo "Common fixes:"
    echo "  - Create dataset first:"
    echo "    curl -X POST ${FUSEKI_URL}/\$/datasets -d 'dbName=${DATASET}&dbType=tdb2'"
    echo "  - Check Fuseki logs for details"
    exit 1
fi

# Verify by running a count query
echo ""
echo "Verifying load..."
COUNT_QUERY="SELECT (COUNT(*) AS ?count) WHERE { GRAPH <${GRAPH_URI}> { ?s ?p ?o } }"

COUNT_RESPONSE=$(curl --silent \
    --header "Accept: application/sparql-results+json" \
    --data-urlencode "query=${COUNT_QUERY}" \
    "${FUSEKI_URL}/${DATASET}/sparql")

TRIPLE_COUNT=$(echo "${COUNT_RESPONSE}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(data['results']['bindings'][0]['count']['value'])
" 2>/dev/null) || TRIPLE_COUNT="unknown"

echo "Loaded ${TRIPLE_COUNT} triples into graph <${GRAPH_URI}>"
echo ""
echo "Query endpoint: ${FUSEKI_URL}/${DATASET}/sparql"
echo "Web UI: ${FUSEKI_URL}/#/dataset/${DATASET}/query"
