#!/usr/bin/env bash

# Load generated RDF Turtle files into a QLever instance.
# Expects QLever to be running and the qlever CLI available.
#
# Unlike the Fuseki loader there is no graph URI to configure: QLever ingests at
# index build time into the default graph, which is where the queries in
# queries/ read from. Nothing here needs to track FG_BASE_URI.
#
# Usage: ./scripts/load_graph_qlever.sh [qlever_endpoint]
# Example: ./scripts/load_graph_qlever.sh http://localhost:7001

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RDF_DIR="${PROJECT_ROOT}/data/output/rdf"
COMBINED_FILE="${RDF_DIR}/faculty-all.ttl"
QLEVER_ENDPOINT="${1:-http://localhost:7001}"

print_usage() {
    echo "Usage: $0 [qlever_endpoint]"
    echo ""
    echo "Load faculty RDF data into QLever."
    echo ""
    echo "Arguments:"
    echo "  qlever_endpoint   QLever SPARQL endpoint URL (default: http://localhost:7001)"
    echo ""
    echo "Prerequisites:"
    echo "  - QLever running and accepting requests at the endpoint"
    echo "  - Combined RDF file generated by: python3 main.py"
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    print_usage
    exit 0
fi

if [[ ! -f "${COMBINED_FILE}" ]]; then
    echo "ERROR: Combined RDF file not found: ${COMBINED_FILE}" >&2
    echo "Run 'python3 main.py' first to generate RDF output." >&2
    exit 1
fi

LINE_COUNT=$(wc -l < "${COMBINED_FILE}")
echo "Loading ${COMBINED_FILE} (${LINE_COUNT} lines) into QLever at ${QLEVER_ENDPOINT}"

# QLever loads data at index build time, not via SPARQL UPDATE.
# Two approaches depending on setup:

# Approach 1: If using qlever CLI tool with an existing Qleverfile
if command -v qlever &> /dev/null; then
    echo "Found qlever CLI. Copying RDF to QLever input directory..."

    # QLever expects input files in its configured data directory.
    # Copy the combined file and rebuild the index.
    QLEVER_DATA_DIR="${QLEVER_DATA_DIR:-${PROJECT_ROOT}/qlever-data}"
    mkdir -p "${QLEVER_DATA_DIR}"
    cp "${COMBINED_FILE}" "${QLEVER_DATA_DIR}/faculty-all.ttl"

    echo "RDF copied to ${QLEVER_DATA_DIR}/faculty-all.ttl"
    echo ""
    echo "Next steps:"
    echo "  cd ${QLEVER_DATA_DIR}"
    echo "  qlever index    # rebuild index with new data"
    echo "  qlever start    # restart server"
    exit 0
fi

# Approach 2: Direct HTTP upload if QLever supports it via POST
echo "No qlever CLI found. Attempting HTTP upload..."

RESPONSE=$(curl --silent --write-out "\n%{http_code}" \
    --request POST \
    --header "Content-Type: text/turtle" \
    --data-binary "@${COMBINED_FILE}" \
    "${QLEVER_ENDPOINT}" 2>&1) || true

HTTP_CODE=$(echo "${RESPONSE}" | tail -1)
BODY=$(echo "${RESPONSE}" | head -n -1)

if [[ "${HTTP_CODE}" == "200" || "${HTTP_CODE}" == "201" ]]; then
    echo "Upload successful (HTTP ${HTTP_CODE})"
    echo "${BODY}"
else
    echo "HTTP upload returned ${HTTP_CODE}. QLever typically loads data at index time." >&2
    echo ""
    echo "Manual steps for QLever:"
    echo "  1. Copy ${COMBINED_FILE} to your QLever data directory"
    echo "  2. Update your Qleverfile to include faculty-all.ttl"
    echo "  3. Run: qlever index && qlever start"
    echo ""
    echo "Server response: ${BODY}"
    exit 1
fi
